
name: Deploy Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "waiters-simulation-api"
          heroku_email: "alejandrogonzalr@gmail.com"
          usedocker: true
